## Source with `source("./scripts/generate_known_tags.R", echo = TRUE, prompt.echo = ">")`

## This script web scrapes two Mozilla websites for HTML and SVG tag elements.
## All HTML tags

library(rvest)
library(dplyr)

# Note: Mozilla seems to have a more up to date set of what is possible / not obsolete compared to W3 schools
base_url <- "https://developer.mozilla.org/en-US/docs/Web"

html_tag_dfs <- read_html(file.path(base_url, "HTML", "Element")) %>%
  html_table()

# The last table is obsolete/deprecated elements
n_dfs <- length(html_tag_dfs)

html_tags_df <- html_tag_dfs[-n_dfs] %>%
  bind_rows() %>%
  # h1-h6 all appear in one comma-separated row
  mutate(name = strsplit(Element, ", ")) %>%
  tidyr::unnest(name) %>%
  select(Element = name, Description) %>%
  transmute(
    name = sub("^<", "", sub(">$", "", Element)),
    desc = paste(
      Description, "Learn more at",
      file.path(base_url, "HTML", "Element", name)
    )
  )

svg <- read_html(file.path(base_url, "SVG", "Element"))

# Due to a lack of structure on the SVG page,
# this seems to be the best way to target just
# the hyperlinks under the "SVG elements A to Z" section
svg_tags <- lapply(letters, function(x) {
  html_elements(svg, sprintf("h3[id=%s] + div > ul > li > a", x)) %>%
    html_attr("href") %>%
    basename()
})

# TODO: evenetually it might be nice to also scrape
# the descriptions by following the url
svg_tags_df <- tibble(
  name = unlist(svg_tags),
  desc = sprintf(
    "Creates the <%s> SVG element. Learn more at %s",
    name, file.path(base_url, "SVG", "Element", name)
  )
)


# Save a JSON version so other languages can read them in easily
cat(
  jsonlite::toJSON(html_tags_df),
  file = "scripts/html_tags.json"
)

cat(
  jsonlite::toJSON(svg_tags_df),
  file = "scripts/svg_tags.json"
)

html_tags <- html_tags_df$name
svg_tags <- svg_tags_df$name


# Both SVG2 and HTML5
svg_tags[svg_tags %in% html_tags]
#> [1] "a"  "script" "style"  "svg"  "title"


new_tags <- c(svg_tags, html_tags) %>%
  unique() %>%
  sort()

# Call using callr::r to avoid any devtools loaded htmltools::tags namespace issues
cran_tags <- callr::r(
  function() {
    remotes::install_cran("htmltools")
    names(htmltools::tags)
  },
  show = TRUE
)

# tags which should not HTML5 / SVG2 supported
setdiff(cran_tags, new_tags)
#> [1] "color-profile" "command"       "eventsource"   "hgroup"
#> [5] "keygen"        "rb"            "rtc"           "solidcolor"


# New HTML5 tags
setdiff(html_tags, cran_tags)
#> "portal" "math"

# New SVG2 tags
setdiff(svg_tags, cran_tags)
#> character(0)

# combine old and new tags so that old tags are not lost
save_tags <- c(new_tags, cran_tags) %>%
  unique() %>%
  sort()

save_line <- paste0(
  format(
    paste0(
      "  \"", save_tags, "\"",
      ifelse(
        seq_along(save_tags) == length(save_tags),
        "", ","
      )
    ),
    justify = "left"
  ),
  "#",
  case_when(
    save_tags %in% html_tags & save_tags %in% svg_tags ~ " html svg",
    save_tags %in% html_tags ~ " html",
    save_tags %in% svg_tags ~  "      svg",
    TRUE ~  "          deprecated"
  )
) %>%
  sub("\\s+$", "", .)
cat(
  "## Generated by `./scripts/generate_known_tags.R`: do not edit by hand",
  "## Please call `source(\"./scripts/generate_known_tags.R\", echo = TRUE, prompt.echo = \">\")` to update",
  "known_tags <- c(",
    paste0(save_line, collapse = "\n"),
  ")",
  sep = "\n",
  file = rprojroot::find_package_root_file(file.path("R", "known_tags.R"))
)
message("Saved to `./R/known_tags.R`")
